# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Terraform infrastructure dependencies
  - package-ecosystem: "terraform"
    directory: "/terraform"
    schedule:
      interval: "daily"
      time: "15:00"
    assignees:
      - "MattWhite-personal"
    commit-message:
      prefix: ":dependabot: "
      prefix-development: ":dependabot: "
      include: "scope"
    pull-request-branch-name:
      separator: "/"
    rebase-strategy: "auto"
    allow:
      - dependency-type: "all"

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "16:00"
    assignees:
      - "MattWhite-personal"
    commit-message:
      prefix: ":dependabot: "
      prefix-development: ":dependabot: "
      include: "scope"
    pull-request-branch-name:
      separator: "/"
    rebase-strategy: "auto"

  # Packer plugin dependencies (via git tags)
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "15:00"
    assignees:
      - "MattWhite-personal"
    commit-message:
      prefix: ":dependabot: "
      include: "scope"
